version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt -t lib
  build:
    commands:
      - echo "Zipping deploynment package..."
      - cd lib
      - zip -r9 ../deploynment_package.zip .
      - cd ..
      - zip -g deploynment_package.zip lambda_function.py
  post_builds:
    commands:
      - echo "Updating lambda function..."
      - aws lambda update_function-code --function-name jenkinslambda --zip-file fileb://deploynment_package
      - echo "DONE!!"         